# Generated by Django 3.2.19 on 2023-07-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistform',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='waitlistform',
            name='phone',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
